name: movie_online
version: 1.0.0+1
publish_to: none
description: movie_online
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  connectivity_plus: ^4.0.1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svg_image/
    - assets/animations/

